twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes:
        - bootstrap_4_layout.html.twig
    globals:
        # le @ pour instancier une instance du Panier
        cart: '@App\Services\Panier'
